// auth actions
export const SET_ERRORS = 'SET_ERRORS';
export const TOGGLE_USER_LOADING = 'TOGGLE_LOADING';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

// vessel actions
export const CREATE_VESSEL = 'CREATE_VESSEL';
export const GET_VESSEL = 'GET_VESSEL';
export const GET_VESSELS = 'GET_VESSELS';
export const UPDATE_VESSEL = 'UPDATE_VESSEL';
export const DELETE_VESSEL = 'DELETE_VESSEL';
export const TOGGLE_VESSEL_LOADING = 'TOGGLE_VESSEL_LOADING';
export const TOGGLE_VESSELS_LOADING = 'TOGGLE_VESSELS_LOADING';
export const RESET_VESSEL = 'RESET_VESSEL';
